### ISSUE TITLE
Please allow for callables not just ListenerInterface

### ISSUE THREAD

**Issue by nesl247** [refinery29/league-lazy-event#22]
Event allows for callables, so league-lazy-event should as well. Otherwise I now have to change my listeners just to have lazy loading.

Thanks!

**Comment by localheinz** [comment]
@nesl247 

Can you elaborate? Happy to look into it!

**Comment by localheinz** [comment]
@nesl247 

Ha, never mind, I think I understand what you mean!

**Comment by localheinz** [comment]
@nesl247 

Wondering, can you show an example of how you create and fetch the listeners?

Just to make sure this can't be solved easier! :smiley:

**Comment by nesl247** [comment]
```php
            'service.event' => function (ServiceManager $serviceManager) {
                $config = $serviceManager->get('config');

                $emitter = new \League\Event\Emitter();

                foreach ($config['listeners'] as $eventName => $listeners) {
                    foreach ($listeners as $listener) {
                        $emitter->addListener(
                            $eventName,
                            \Refinery29\Event\LazyListener::fromAlias($listener, $serviceManager)
                        );
                    }
                }

                return $emitter;
            },
```

**Comment by nesl247** [comment]
I mean the whole issue is that you are checking for a listener to implement an interface. This goes against the flexibility of the event library.

**Comment by localheinz** [comment]
@nesl247 

No worries, we'll sort it out! Out of curiosity, are you using ZF2 there?

**Comment by nesl247** [comment]
Using Zend Expressive with Zend Service Manager.

**Comment by localheinz** [comment]
Nice!

**Comment by nesl247** [comment]
I already have my working version of it here https://github.com/nesl247/league-lazy-event/commit/a93d3b3cbf3423f274a7b11db516a6f3deeb8d7c. I just didn't write any unit tests for it, thus I didn't want to submit a PR. It could probably also be done in a cleaner way, but it got me up and running quickly enough.

I'm actually surprised Event doesn't have this built into it.
